In [3]:
import numpy as np

import pandas as pd

**1**

In [8]:
df = pd.read_csv('estudiantes.csv')

In [9]:
print (df.head(10))

             Nombre  Edad  Nota Departamento
0    Julia Reátegui  23.0  15.1         Lima
1   Lucía Velásquez  21.0  17.3         Puno
2     Luis Alvarado  20.0   5.6         Lima
3     Alonso Vargas  23.0   7.7  La Libertad
4  Fiorella Aguirre  22.0  18.5        Pasco
5       Raúl Ticona  22.0  15.8        Cusco
6       José Vargas  16.0  15.2       Áncash
7   Fiorella Zapata  16.0  11.4       Loreto
8      Rocío Vargas  22.0  10.7        Piura
9    Andrés Pizarro  21.0  13.0        Piura

In [10]:
print (df.tail(5))

               Nombre  Edad  Nota  Departamento
195     Álvaro Chávez  21.0   9.5    San Martín
196       Percy Tapia  22.0  13.3       Ucayali
197    Juan Chumpitaz  19.0  12.2  Huancavelica
198     Paola Linares  20.0   5.4         Piura
199  Fernando Pariona  23.0  15.7       Ucayali

**2**

In [13]:
df.shape

(200, 4)

In [15]:
df.columns

Index(['Nombre', 'Edad', 'Nota', 'Departamento'], dtype='object')

In [21]:
df.dtypes

Nombre           object
Edad            float64
Nota            float64
Departamento     object
dtype: object

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Nombre        200 non-null    object
 1   Edad          197 non-null    float64
 2   Nota          194 non-null    float64
 3   Departamento  200 non-null    object
dtypes: float64(2), object(2)
memory usage: 6.4+ KB

**3**

In [23]:
df.describe().round(2)

         Edad    Nota
count  197.00  194.00
mean    21.11   12.81
std      3.01    3.56
min     16.00    2.20
25%     19.00   10.10
50%     21.00   13.00
75%     23.00   15.30
max     30.00   20.00

**4**

In [51]:
conteo = df['Departamento'].value_counts()

print(conteo)

print((df['Departamento'].nunique()))

Departamento
Lima             43
Piura            16
Cusco            15
Arequipa         10
Lambayeque       10
Junín             9
San Martín        9
Ucayali           9
Pasco             8
La Libertad       8
Tacna             8
Áncash            7
Puno              7
Loreto            7
Callao            6
Madre de Dios     5
Tumbes            5
Moquegua          4
Ica               4
Cajamarca         3
Apurímac          2
Amazonas          2
Huánuco           1
Ayacucho          1
Huancavelica      1
Name: count, dtype: int64
25

**5**

In [52]:
faltantes = df.isna().sum()
porcentaje = df.isna().sum() / len(df) * 100

print(faltantes)
print(porcentaje)

filas_afectadas = df[df.isna().any(axis=1)]
print(filas_afectadas)

Nombre          0
Edad            3
Nota            6
Departamento    0
dtype: int64
Nombre          0.0
Edad            1.5
Nota            3.0
Departamento    0.0
dtype: float64
                Nombre  Edad  Nota Departamento
19    Valeria Espinoza   NaN  10.2         Puno
36       Miguel Zapata   NaN   9.1     Arequipa
114  Katherine Sánchez  26.0   NaN         Lima
117         Ana Chávez  21.0   NaN         Lima
120         Hugo Tapia  18.0   NaN     Amazonas
127     Carmen Aguirre  18.0   NaN        Piura
138  Estefanía Nolasco   NaN  11.8    Cajamarca
150     Brenda Paredes  16.0   NaN         Lima
187        Wilder Meza  20.0   NaN     Moquegua

**6**

In [54]:
df_limpio = df.dropna(subset=["Nota"]).copy()

mediana_edad = df_limpio["Edad"].median()

df_limpio["Edad"] = df_limpio["Edad"].fillna(mediana_edad)

print(df_limpio.isna().sum())
print(df_limpio.shape)

Nombre          0
Edad            0
Nota            0
Departamento    0
dtype: int64
(194, 4)

**7**

In [57]:
notas = df_limpio["Nota"].to_numpy()
edades = df_limpio["Edad"].to_numpy()

print("NOTA")
print(np.mean(notas).round(2))
print(np.median(notas).round(2))
print(np.std(notas).round(2))
print(np.var(notas).round(2))

print("EDAD")
print(np.mean(edades).round(2))
print(np.median(edades).round(2))
print(np.std(edades).round(2))
print(np.var(edades).round(2))

NOTA
12.81
13.0
3.55
12.61
EDAD
21.14
21.0
2.96
8.76

**8**

In [58]:
print("NOTAS")
print("Mínimo:", np.min(notas))
print("Máximo:", np.max(notas))
print("Rango:", np.ptp(notas))
print("Q1:", np.percentile(notas, 25))
print("Q2:", np.percentile(notas, 50))
print("Q3:", np.percentile(notas, 75))

print("EDADES")
print("Mínimo:", np.min(edades))
print("Máximo:", np.max(edades))
print("Rango:", np.ptp(edades))
print("Q1:", np.percentile(edades, 25))
print("Q2:", np.percentile(edades, 50))
print("Q3:", np.percentile(edades, 75))

NOTAS
Mínimo: 2.2
Máximo: 20.0
Rango: 17.8
Q1: 10.1
Q2: 13.0
Q3: 15.3
EDADES
Mínimo: 16.0
Máximo: 30.0
Rango: 14.0
Q1: 19.0
Q2: 21.0
Q3: 23.0

In [139]:
df_limpio["Nota"].mean().round(2)

np.float64(12.81)

In [154]:
np.nanmean(df["Nota"].to_numpy())

np.float64(12.807731958762886)

**9**

In [59]:
maximo = np.max(notas)
minimo = np.min(notas)

mejores = df_limpio[
    df_limpio["Nota"] == maximo
][["Nombre", "Edad", "Nota", "Departamento"]]

peores = df_limpio[
    df_limpio["Nota"] == minimo
][["Nombre", "Edad", "Nota", "Departamento"]]

print(mejores)
print(peores)

              Nombre  Edad  Nota   Departamento
40     Julia Linares  20.0  20.0    La Libertad
111    Néstor Vargas  21.0  20.0  Madre de Dios
122  Marco Chumpitaz  23.0  20.0          Junín
171    Yolanda Ávila  27.0  20.0          Cusco
175   Yolanda Huamán  24.0  20.0         Áncash
              Nombre  Edad  Nota Departamento
106  Marco Chumpitaz  21.0   2.2     Arequipa

**10**

In [81]:
aprobados = df_limpio[df_limpio["Nota"] >= 11]
desaprobados = df_limpio[df_limpio["Nota"] < 11]

tasa = round(len(aprobados) / len(df_limpio) * 100,2)

print("Aprobados:", len(aprobados))
print("Desaprobados:", len(desaprobados))
print("Tasa:", tasa)

Aprobados: 132
Desaprobados: 62
Tasa: 68.04

**11**

In [82]:
df_limpio["Aprobado"] = np.where(
    df_limpio["Nota"] >= 11,
    "Sí",
    "No"
)

print(df_limpio["Aprobado"].value_counts())

Aprobado
Sí    132
No     62
Name: count, dtype: int64

**12**

In [83]:
seleccion = df_limpio[
    (df_limpio["Edad"] < 20) &
    (df_limpio["Nota"] >= 15)
]

print(seleccion)

                Nombre  Edad  Nota Departamento Aprobado
6          José Vargas  16.0  15.2       Áncash       Sí
17         Rocío Ávila  19.0  15.3        Cusco       Sí
29      Iván Chumpitaz  16.0  15.2       Callao       Sí
32        Rocío Zapata  19.0  17.9         Lima       Sí
33     Patricia Huamán  19.0  15.5   San Martín       Sí
39       Juan Ccahuana  17.0  15.5   Lambayeque       Sí
76    Gabriela Ordóñez  19.0  17.2   San Martín       Sí
94       Alonso Farfán  16.0  15.9         Lima       Sí
104      Andrés Mamani  19.0  16.1         Lima       Sí
119     Wilder Pizarro  19.0  15.0         Lima       Sí
123  Camila Bustamante  18.0  15.5        Cusco       Sí
131       Percy Mamani  19.0  16.1         Lima       Sí
139     Diego Alvarado  19.0  18.6        Piura       Sí
141        Karla Ramos  19.0  17.5     Arequipa       Sí
172     Katherine Ríos  19.0  15.2        Pasco       Sí
177       Karla Farfán  19.0  16.7     Apurímac       Sí
179   Melissa Espinoza  16.0  17.4  La Libertad       Sí
180      Diego Salazar  19.0  17.0       Callao       Sí

**13**

In [94]:
top10 = df_limpio.sort_values ("Nota", ascending=False).head(10)

print(top10)

               Nombre  Edad  Nota   Departamento Aprobado
40      Julia Linares  20.0  20.0    La Libertad       Sí
122   Marco Chumpitaz  23.0  20.0          Junín       Sí
175    Yolanda Huamán  24.0  20.0         Áncash       Sí
171     Yolanda Ávila  27.0  20.0          Cusco       Sí
111     Néstor Vargas  21.0  20.0  Madre de Dios       Sí
23      Álvaro Guzmán  24.0  19.8           Lima       Sí
71      Sergio Farfán  21.0  19.5           Lima       Sí
51     Fiorella Rojas  29.0  19.1        Ucayali       Sí
15        Lucía Tapia  22.0  19.0         Tumbes       Sí
18   Carmen Maldonado  24.0  18.7           Lima       Sí

**14**

In [100]:
promedios = (df_limpio.groupby("Departamento")["Nota"].mean().round(2).sort_values(ascending=False))

print(promedios)

Departamento
Apurímac         15.80
Ucayali          14.97
Madre de Dios    14.92
Cajamarca        14.63
Áncash           14.47
Callao           13.78
Tumbes           13.70
Cusco            13.55
Pasco            13.52
La Libertad      13.02
Ayacucho         13.00
Lima             12.52
Junín            12.39
San Martín       12.26
Puno             12.23
Ica              12.22
Huancavelica     12.20
Loreto           12.10
Arequipa         12.00
Lambayeque       11.91
Tacna            11.88
Moquegua         11.70
Piura            11.65
Huánuco          10.70
Amazonas         10.20
Name: Nota, dtype: float64

**15**

In [102]:
tabla = pd.crosstab(
    df_limpio["Departamento"],
    df_limpio["Aprobado"]
)

tabla["Total"] = tabla["Sí"] + tabla["No"]

tabla["Tasa"] = (tabla["Sí"] / tabla["Total"] * 100).round(2)

tabla = tabla.sort_values(
    "Tasa",
    ascending=False
)

print(tabla)

Aprobado       No  Sí  Total    Tasa
Departamento
Apurímac        0   2      2  100.00
Cajamarca       0   3      3  100.00
Ayacucho        0   1      1  100.00
Huancavelica    0   1      1  100.00
Madre de Dios   0   5      5  100.00
Ucayali         1   8      9   88.89
Loreto          1   6      7   85.71
Callao          1   5      6   83.33
Cusco           3  12     15   80.00
Pasco           2   6      8   75.00
Ica             1   3      4   75.00
Áncash          2   5      7   71.43
Arequipa        3   7     10   70.00
Moquegua        1   2      3   66.67
Tacna           3   5      8   62.50
Lima           15  25     40   62.50
La Libertad     3   5      8   62.50
Tumbes          2   3      5   60.00
Lambayeque      4   6     10   60.00
Puno            3   4      7   57.14
Junín           4   5      9   55.56
San Martín      4   5      9   55.56
Piura           7   8     15   53.33
Huánuco         1   0      1    0.00
Amazonas        1   0      1    0.00

**16**

In [103]:
df_limpio["GrupoEtario"] = pd.cut(
    df_limpio["Edad"],
    bins=[15, 19, 22, 25, np.inf],
    labels=["16-19", "20-22", "23-25", "26+"]
)

resumen_edad = df_limpio.groupby(
    "GrupoEtario",
    observed=False
)["Nota"].agg(
    Cantidad="count",
    Promedio="mean",
    Mediana="median"
)

print(resumen_edad)

             Cantidad   Promedio  Mediana
GrupoEtario
16-19              62  12.645161    13.05
20-22              76  12.767105    12.95
23-25              39  13.107692    13.70
26+                17  12.894118    12.80

**17**

In [110]:
condiciones = [
    df_limpio["Nota"] >= 18,
    df_limpio["Nota"] >= 14,
    df_limpio["Nota"] >= 11,
    df_limpio["Nota"] >= 0
]

categorias = ["AD", "A", "B", "C"]

df_limpio["Escala"] = np.select(
    condiciones,
    categorias,
    default="C"
)

conteo = df_limpio["Escala"].value_counts()
porcentaje = conteo / len(df_limpio) * 100

print(conteo)
print(porcentaje)

Escala
A     63
C     62
B     56
AD    13
Name: count, dtype: int64
Escala
A     32.474227
C     31.958763
B     28.865979
AD     6.701031
Name: count, dtype: float64

**18**

In [111]:
tabla_cruzada = pd.crosstab(
    df_limpio["GrupoEtario"],
    df_limpio["Aprobado"],
    margins=True
)

print(tabla_cruzada)

Aprobado     No   Sí  All
GrupoEtario
16-19        16   46   62
20-22        28   48   76
23-25        12   27   39
26+           6   11   17
All          62  132  194

In [120]:
porcentajes = pd.crosstab(
    df_limpio["GrupoEtario"],
    df_limpio["Aprobado"],
    normalize="index"
) * 100

print(porcentajes)

Aprobado            No         Sí
GrupoEtario
16-19        25.806452  74.193548
20-22        36.842105  63.157895
23-25        30.769231  69.230769
26+          35.294118  64.705882

**19**

In [123]:
minimo = df_limpio["Nota"].min()
maximo = df_limpio["Nota"].max()

df_limpio["Nota_minmax"] = (
    (df_limpio["Nota"] - minimo)
    /
    (maximo - minimo)
)
print(df_limpio["Nota_minmax"].round(2))

0      0.72
1      0.85
2      0.19
3      0.31
4      0.92
       ...
195    0.41
196    0.62
197    0.56
198    0.18
199    0.76
Name: Nota_minmax, Length: 194, dtype: float64

In [126]:
media = np.mean(df_limpio["Nota"])
desviacion = np.std(df_limpio["Nota"])

df_limpio["Nota_z"] = (
    (df_limpio["Nota"] - media)
    /
    desviacion
)
print(df_limpio["Nota_z"].round(2))

0      0.65
1      1.26
2     -2.03
3     -1.44
4      1.60
       ...
195   -0.93
196    0.14
197   -0.17
198   -2.09
199    0.81
Name: Nota_z, Length: 194, dtype: float64

In [128]:
atipicos = df_limpio[
    np.abs(df_limpio["Nota_z"]) > 2
]

print(atipicos[
    ["Nombre", "Nota", "Departamento", "Nota_z"]
].round(2))

                Nombre  Nota   Departamento  Nota_z
2        Luis Alvarado   5.6           Lima   -2.03
40       Julia Linares  20.0    La Libertad    2.03
78         Ana Nolasco   5.1           Lima   -2.17
106    Marco Chumpitaz   2.2       Arequipa   -2.99
111      Néstor Vargas  20.0  Madre de Dios    2.03
122    Marco Chumpitaz  20.0          Junín    2.03
171      Yolanda Ávila  20.0          Cusco    2.03
173  Milagros Reátegui   5.7          Piura   -2.00
175     Yolanda Huamán  20.0         Áncash    2.03
198      Paola Linares   5.4          Piura   -2.09

**20**

In [129]:
reporte = (
    df_limpio.groupby("Departamento")
    .agg(
        Estudiantes=("Nota", "size"),
        Nota_promedio=("Nota", "mean"),
        Mediana=("Nota", "median"),
        Desviacion_estandar=("Nota", "std"),
        Minimo=("Nota", "min"),
        Maximo=("Nota", "max"),
        Aprobados=("Aprobado", lambda x: (x == "Sí").sum()),
        Desaprobados=("Aprobado", lambda x: (x == "No").sum())
    )
)

reporte["Tasa_aprobacion"] = (
    reporte["Aprobados"]
    / reporte["Estudiantes"]
    * 100
)

reporte = reporte[
    reporte["Estudiantes"] >= 5
]

reporte = reporte.sort_values(
    "Tasa_aprobacion",
    ascending=False
)

reporte = reporte.round(2)

print(reporte)

               Estudiantes  Nota_promedio  Mediana  Desviacion_estandar  \
Departamento
Madre de Dios            5          14.92    14.20                 3.23
Ucayali                  9          14.97    14.60                 2.78
Loreto                   7          12.10    11.50                 3.00
Callao                   6          13.78    14.35                 2.77
Cusco                   15          13.55    14.30                 3.26
Pasco                    8          13.52    14.45                 3.61
Áncash                   7          14.47    14.20                 3.95
Arequipa                10          12.00    12.85                 4.71
Lima                    40          12.52    12.95                 3.94
La Libertad              8          13.02    13.40                 4.60
Tacna                    8          11.88    11.90                 3.01
Tumbes                   5          13.70    11.60                 4.20
Lambayeque              10          11.91    12.10                 3.33
Puno                     7          12.23    11.40                 3.08
Junín                    9          12.39    12.40                 3.24
San Martín               9          12.26    11.80                 3.70
Piura                   15          11.65    12.70                 4.04

               Minimo  Maximo  Aprobados  Desaprobados  Tasa_aprobacion
Departamento
Madre de Dios    11.2    20.0          5             0           100.00
Ucayali          10.4    19.1          8             1            88.89
Loreto            7.2    16.0          6             1            85.71
Callao           10.0    17.0          5             1            83.33
Cusco             7.4    20.0         12             3            80.00
Pasco             7.3    18.5          6             2            75.00
Áncash            9.3    20.0          5             2            71.43
Arequipa          2.2    17.5          7             3            70.00
Lima              5.1    19.8         25            15            62.50
La Libertad       6.9    20.0          5             3            62.50
Tacna             7.2    15.3          5             3            62.50
Tumbes            9.7    19.0          3             2            60.00
Lambayeque        6.6    16.8          6             4            60.00
Puno              9.1    17.3          4             3            57.14
Junín             8.9    20.0          5             4            55.56
San Martín        8.2    17.2          5             4            55.56
Piura             5.4    18.6          8             7            53.33

In [137]:
reporte.to_csv(
    "reporte.csv",
    index=False,
    encoding="utf-8"
)

verificacion = pd.read_csv("reporte.csv")

print(verificacion.head())

   Estudiantes  Nota_promedio  Mediana  Desviacion_estandar  Minimo  Maximo  \
0            5          14.92    14.20                 3.23    11.2    20.0
1            9          14.97    14.60                 2.78    10.4    19.1
2            7          12.10    11.50                 3.00     7.2    16.0
3            6          13.78    14.35                 2.77    10.0    17.0
4           15          13.55    14.30                 3.26     7.4    20.0

   Aprobados  Desaprobados  Tasa_aprobacion
0          5             0           100.00
1          8             1            88.89
2          6             1            85.71
3          5             1            83.33
4         12             3            80.00